### ISSUE TITLE
Migration to flutter 3.

### ISSUE THREAD

**Issue by cedvdb** [qiuxiang/cross_file_image#2]
This PR did not pass but it is a valid migration to flutter 3 (but is incomplete):

https://github.com/qiuxiang/cross_file_image/pull/1/files

**Comment by qiuxiang** [comment]
resolve in v0.0.2

**Comment by cedvdb** [comment]
@qiuxiang You forgot to add flutter 3.0.0 in the pubspec, it's going to break apps  that are not flutter 3 if you fix the warning properly without doing that.

A breaking change is also a good place to increment the version (v1.0.0).

The warning message is still present after your update too

**Comment by qiuxiang** [comment]
i dont think it needs to add flutter 3.0.0 in the pubspec. i have upgraded flutter to v3 and this package works fine.

**Comment by cedvdb** [comment]
it does not work fine

![image](https://user-images.githubusercontent.com/22280985/169813784-cfa64158-0819-45ef-9276-bc2808ae662a.png)

> i dont think it needs to add flutter 3.0.0 in the pubspec

Yes you have to , else it's a breaking change if you correct the above warning.
